In [ ]:
import numpy as np



```
numpy = numeric python ```



In [ ]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
np2 = np.arange(10)
print(np2)
np3 = np.arange(0,50, 5)
print(np3)
np4=np.zeros(50)
print(np4)
np5=np.zeros((2,10))
print(np5)
np6 = np.full((10),2)
print(np6)
np7 = np.full((10,2),6)
print(np7)
my_list = [1,2,3,4,5]
np8= np.array(my_list)
print(np8[2])


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  5 10 15 20 25 30 35 40 45]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[2 2 2 2 2 2 2 2 2 2]
[[6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [6 6]]
3


In [ ]:
np1 = np.array([1,2,3,4,5,6,7,8,9])
print(np1[1:5])
print(np1[3:])
print(np1[-3:-1])
print(np1[1:5:2]) # stepzss of 2
print(np1[::2]) # stepzss of 2
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2[1,2])  # (row :column)
print (np2[0:1,:3])

[2 3 4 5]
[4 5 6 7 8 9]
[7 8]
[2 4]
[1 3 5 7 9]
8
[[1 2 3]]


In [ ]:
np1 = np.array([1,2,3,4,5,6,7,8,9])
print(np1)
print(np.sqrt(np1))
print(np.absolute(np1))
print(np.exp(np1))
print(np.min(np1))
print(np.max(np1))
print(np.sign(np1))
print(np.sin(np1))
print(np.cos(np1))
print(np.tan(np1))

[1 2 3 4 5 6 7 8 9]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[1 2 3 4 5 6 7 8 9]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
1
9
[1 1 1 1 1 1 1 1 1]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]


In [ ]:
np1 = np.array([0,1,2,3,4,5])
print(np1)
np2=np1.view()
print(np2)
print(f'Original NP1 {np1}')
print(f'Original NP2 {np2}')
np1[0]=33
print(f'changed NP1 {np1}')
print(f'changed NP2 {np2}') # when we change in the array the view changes automatically


[0 1 2 3 4 5]
[0 1 2 3 4 5]
Original NP1 [0 1 2 3 4 5]
Original NP2 [0 1 2 3 4 5]
changed NP1 [33  1  2  3  4  5]
changed NP2 [33  1  2  3  4  5]


In [ ]:
np1 = np.array([0,1,2,3,4,5])
print(np1)
np2=np1.copy()
print(np2)
print(f'Original NP1 {np1}')
print(f'Original NP2 {np2}')
np1[0]=33
print(f'changed NP1 {np1}')
print(f'changed NP2 {np2}') # when we change in the array the copy does not changes automatically

[0 1 2 3 4 5]
[0 1 2 3 4 5]
Original NP1 [0 1 2 3 4 5]
Original NP2 [0 1 2 3 4 5]
changed NP1 [0 1 2 3 4 5]
changed NP2 [33  1  2  3  4  5]


In [ ]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)
print(np1.shape)


np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2)
print(np2.shape)


np3 = np1.reshape(3,4)
print(np3)
print(np3.shape)


np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)


np5 = np4.reshape(-1)
print(np5)
print(np5.shape)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np1)
for x in np1:
 print(x)



 np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2)
for x in np2:
  for y in x:
    print(y)
  #print rows
 #print(x)





 #use np.nditer()
for x in np.nditer(np2):
  print(x)

[ 1  2  3  4  5  6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [ ]:
np1 = np.array([6,7,4,9,0,2,1])
print(np1)
print(np.sort(np1))
np1=np.sort(np1)
print(np1)

np2 = np.array(["d","a","b","c"])
print(np2)
print(np.sort(np2))

np4 = np.array([[6,7,1,9],[8,3,5,0]])
print(np4)
print(np.sort(np4))

[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]
[0 1 2 4 6 7 9]
['d' 'a' 'b' 'c']
['a' 'b' 'c' 'd']
[[6 7 1 9]
 [8 3 5 0]]
[[1 6 7 9]
 [0 3 5 8]]


In [ ]:
np1 = np.array([1,2,3,4,5,6,7,8,9,3,3,3,3])
print(np1)
x=np.where(np1==3)
print(x)
print(np1[x[0]])
y=np.where(np1 % 2 == 0 )
print(y)

[1 2 3 4 5 6 7 8 9 3 3 3 3]
(array([ 2,  9, 10, 11, 12]),)
[3 3 3 3 3]
(array([1, 3, 5, 7]),)


In [ ]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np1)
x=[True,True,False,False,False,True,True,True,True,True,]
print(np1[x])



filtered=[]
for thing in np1:
  if thing % 2 == 0:
    filtered.append(True)
  else :
    filtered.append(False)
print(np1)
print (filtered)
new = np1[filtered]
print(np1[filtered])





filtered = np1 % 2 == 0
print (filtered)
new = np1[filtered]
print(np1[filtered])


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
